import { FC } from "react"
import Head from 'next/head'
import { Navbar } from "../Navbar"
import styles from './main.module.css'



export const MainLayout: FC = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Guillermo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>

        {children}
      </main>


    </div>
  )
}
